package template

import (
	"text/template"
)

var PackageTemplate = template.Must(template.New("").Parse(`// Code generated by go-localize; DO NOT EDIT.
// This file was generated by robots at
// {{ .Timestamp }}

package {{ .Package }}

import (
	"mimir/corelib/i18n"
)


var l = i18n.New("en", "en", localizations)

func GetWithLocale(locale string, key i18n.Key, replacements ...*i18n.Replacements) string {
	return l.GetWithLocale(locale, key, replacements...)
}

const (
{{- range $key, $element := .Keys }}
	{{ $key }} i18n.Key = "{{ $element }}"
{{- end }}
)

var localizations = map[string]string{
{{- range $key, $element := .Localizations }}
	"{{ $key }}": "{{ $element }}",
{{- end }}
}
`,
))
