package main

import (
	"text/template"
)

var packageTemplate = template.Must(template.New("").Parse(`// Code generated by go-localize; DO NOT EDIT.
// This file was generated by robots at
// {{ .Timestamp }}

package {{ .Package }}

const (
{{- range $key, $element := .Keys }}
	{{ $key }} = "{{ $element }}"
{{- end }}
)

var localizations = map[string]string{
{{- range $key, $element := .Localizations }}
	"{{ $key }}": "{{ $element }}",
{{- end }}
}
`,
))
